<a href="https://colab.research.google.com/github/ranjithrajappa/pytorch-for-deep-learning-and-machine-learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('hello')



hello


In [ ]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
print(torch.__version__)

2.10.0+cpu


**### Introduction to tensors**

In [ ]:
## Introduction to tensors

# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as python int

scalar.item()

7

In [ ]:
# vector
vector=torch.tensor([4,5,6])
vector

tensor([4, 5, 6])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([3])

In [ ]:
# MATRIX

MATRIX = torch.tensor([[2,3,4],[1,2,3],[1,2,3]])
MATRIX

tensor([[2, 3, 4],
        [1, 2, 3],
        [1, 2, 3]])

In [ ]:
MATRIX.ndim  #based on the square bracket pairs - it is 2

2

In [ ]:
MATRIX.shape

torch.Size([3, 3])

In [ ]:
MATRIX[0]

tensor([2, 3, 4])

In [ ]:
print(MATRIX)
print(f"MATRIX[0]:",MATRIX[0])
print(f"MATRIX[1]:",MATRIX[1])
print(f"MATRIX[2]",MATRIX[2])


tensor([[2, 3, 4],
        [1, 2, 3],
        [1, 2, 3]])
MATRIX[0]: tensor([2, 3, 4])
MATRIX[1]: tensor([1, 2, 3])
MATRIX[2] tensor([1, 2, 3])


In [ ]:
#TENSOR
TENSOR = torch.tensor([[[2,3,4],
                        [1,2,3]
                        ]])
TENSOR

tensor([[[2, 3, 4],
         [1, 2, 3]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 2, 3])

In [ ]:
print(TENSOR)
print("TENSOR[0]:",TENSOR[0])



tensor([[[2, 3, 4],
         [1, 2, 3]]])
TENSOR[0]: tensor([[2, 3, 4],
        [1, 2, 3]])


### Random tensors
## what are they




In [ ]:
## create a random tensor of size (3,4)
rand_tensor=torch.rand(3,4)
rand_tensor

tensor([[0.2692, 0.7794, 0.9663, 0.1796],
        [0.0168, 0.5280, 0.6338, 0.2518],
        [0.5932, 0.9430, 0.4716, 0.0975]])

In [ ]:
### scalar?
scalar_rand=torch.rand(1)
scalar_rand

tensor([0.8877])

In [ ]:


tensor1 = torch.rand(4,3,1)
tensor1

tensor([[[0.0562],
         [0.8282],
         [0.5561]],

        [[0.6382],
         [0.5683],
         [0.1989]],

        [[0.2697],
         [0.4102],
         [0.7195]],

        [[0.7169],
         [0.4991],
         [0.8776]]])

In [ ]:
tensor2=torch.rand(3,2)
tensor2


tensor([[0.8185, 0.3194],
        [0.6951, 0.2015],
        [0.1725, 0.9458]])

In [ ]:
tensor3=torch.rand(2)
tensor3

tensor([0.0203, 0.7606])

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=[3,224,224]) # the 3 in dim 0 represents the 3 colour channels - red,green and blue
print(random_image_tensor)
random_image_tensor.ndim, random_image_tensor.shape

tensor([[[0.4716, 0.2619, 0.7157,  ..., 0.8152, 0.8183, 0.7164],
         [0.9488, 0.0767, 0.7889,  ..., 0.7189, 0.6784, 0.1981],
         [0.7313, 0.0651, 0.2710,  ..., 0.1868, 0.1980, 0.6715],
         ...,
         [0.9766, 0.1616, 0.1122,  ..., 0.9895, 0.4170, 0.5065],
         [0.2946, 0.8502, 0.7765,  ..., 0.1270, 0.1211, 0.0065],
         [0.7264, 0.6286, 0.1487,  ..., 0.9577, 0.2216, 0.1895]],

        [[0.2602, 0.4026, 0.2100,  ..., 0.4217, 0.6671, 0.8780],
         [0.0538, 0.4827, 0.5050,  ..., 0.5304, 0.9593, 0.8335],
         [0.7767, 0.7874, 0.4210,  ..., 0.6184, 0.1292, 0.6670],
         ...,
         [0.0379, 0.6588, 0.3791,  ..., 0.7661, 0.9061, 0.8320],
         [0.0060, 0.6063, 0.6749,  ..., 0.5473, 0.1589, 0.5315],
         [0.1227, 0.4986, 0.4028,  ..., 0.4164, 0.1241, 0.4532]],

        [[0.7998, 0.0589, 0.5355,  ..., 0.4238, 0.9257, 0.5220],
         [0.5563, 0.5039, 0.9137,  ..., 0.8494, 0.4627, 0.6181],
         [0.4998, 0.0325, 0.8644,  ..., 0.1913, 0.5792, 0.

(3, torch.Size([3, 224, 224]))

In [ ]:
rand_tensor_1=torch.rand([5,4,3,2,1])   # to visualize tensors
print(rand_tensor_1, rand_tensor_1.shape, rand_tensor_1.ndim)

tensor([[[[[8.7020e-01],
           [1.7518e-01]],

          [[3.7183e-01],
           [2.0411e-01]],

          [[7.1922e-01],
           [9.2588e-01]]],


         [[[3.1507e-01],
           [1.2373e-01]],

          [[6.3179e-01],
           [5.3748e-01]],

          [[4.4189e-01],
           [5.8142e-01]]],


         [[[8.0964e-01],
           [8.1334e-01]],

          [[9.4061e-02],
           [2.4753e-01]],

          [[7.4501e-01],
           [7.9775e-01]]],


         [[[4.2596e-02],
           [4.6192e-02]],

          [[9.7296e-01],
           [2.3834e-01]],

          [[4.0865e-01],
           [4.2036e-01]]]],



        [[[[8.3699e-01],
           [8.5906e-01]],

          [[4.2062e-01],
           [8.0233e-01]],

          [[8.5256e-01],
           [4.3277e-01]]],


         [[[2.7142e-01],
           [5.6036e-01]],

          [[6.9294e-01],
           [4.1567e-01]],

          [[1.2189e-01],
           [5.1945e-02]]],


         [[[6.3650e-01],
           [2.3794e-01]],

###Zeros and ones



In [ ]:
# Create a tensor of zeros
zeros=torch.zeros(3,4)
print(zeros)
print(zeros.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32


In [ ]:
zer1=torch.zeros(size=[2,3,1])
print(zer1)
print(zer1.dtype)

tensor([[[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]]])
torch.float32


In [ ]:
ones=torch.ones(3,4)
print(ones)
print(ones.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


In [ ]:
new_tensor=torch.rand(3,4)
new_tensor_0=zeros*new_tensor
new_tensor_1=ones*new_tensor
print(new_tensor)
print(new_tensor_0)
print(new_tensor_1)

tensor([[0.0178, 0.9465, 0.7399, 0.1924],
        [0.8121, 0.2230, 0.9809, 0.8248],
        [0.6499, 0.9233, 0.5944, 0.3713]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0.0178, 0.9465, 0.7399, 0.1924],
        [0.8121, 0.2230, 0.9809, 0.8248],
        [0.6499, 0.9233, 0.5944, 0.3713]])


### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range() and get deprecated message, use torch.arange() instead as per UserWarning
torch.range(0,10)

/tmp/ipykernel_167/3706779760.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.arange(10,0,-1)

tensor([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
torch.arange(20.4,2.5,-2)

tensor([20.4000, 18.4000, 16.4000, 14.4000, 12.4000, 10.4000,  8.4000,  6.4000,
         4.4000])

In [ ]:
# Creating tensors like
a=torch.tensor([[1,2,3],[4,5,6]])
b=torch.arange(22,44,2)
c=torch.zeros_like(a)   # input for zeros_like function is a tensor
print(c)
d=torch.zeros_like(input=b)
print(d)
e=torch.ones_like(d)  # input for ones_like function is a tensor
print(e)

tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


#Tensor Datatypes
### Note: Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not right device

In [ ]:
# Float 32 tensor (default)
float_32_tensor = torch.tensor([1.0,2.0,3.2],
                               dtype=None,# what datatype is the tensor ex:float32(default) or float16
                               device=None,# what device is your tensor on ex: cpu(default) or cuda
                               requires_grad=False) # whether or not to track gradients with this tensor's operations
print(float_32_tensor)
print(float_32_tensor.dtype)
print(float_32_tensor.device)

# The default datatype is going to come out as float32 even if dtype is specified as None ( and float type numbers are used to create tensor).
# 'FP32' or 'float32' or '32-bit floating point' or 'single-precision floating point format'
# 'FP16' or 'float16' or '16-bit floating point' or 'half-precision floating point format'
# 'FP64' or 'float64' or '64-bit floating point' or 'double-precision floating point format'

#In computer science, precision refers to how accurately a computer can represent and calculate numbers, especially decimal or fractional values.
# It’s about how many digits (or bits) are used to store a number, which determines how close the stored value is to the actual mathematical value.

tensor([1.0000, 2.0000, 3.2000])
torch.float32
cpu


In [ ]:
# Convertin float32 to another dtype
float_16_tensor_a=float_32_tensor.type(torch.float16) #A torch.dtype is an object that represents the data type of a torch.Tensor.
float_16_tensor_b=float_32_tensor.type(torch.half)
print(float_16_tensor_a,float_16_tensor_a.dtype)
print(float_16_tensor_b,float_16_tensor_b.dtype)


tensor([1.0000, 2.0000, 3.1992], dtype=torch.float16) torch.float16
tensor([1.0000, 2.0000, 3.1992], dtype=torch.float16) torch.float16


In [ ]:
#defining the dtype while creating the tensor, if it shouldn't be default float32
float_64_tensor= torch.tensor([2.0,3.0,4.0],
                                dtype=torch.float64,
                                )
float_64_tensor.dtype

torch.float64

In [ ]:
d=float_32_tensor*float_64_tensor
e=float_32_tensor+float_64_tensor
print(float_32_tensor,float_64_tensor)
print(d,d.dtype)
print(e,e.dtype)

tensor([1.0000, 2.0000, 3.2000]) tensor([2., 3., 4.], dtype=torch.float64)
tensor([ 2.0000,  6.0000, 12.8000], dtype=torch.float64) torch.float64
tensor([3.0000, 5.0000, 7.2000], dtype=torch.float64) torch.float64



Getting information from tensors(Tensor attributes):

1.	Tensors not right datatype – to get datatype from a tensor, type tensor.dtype

2.	Tensors not right shape – to get shape from a tensor, type tensor.shape

3.	Tensors not right device – to get device from a tensor, type tensor.device


In [ ]:
tensor_mat=torch.tensor([[1,2]])
print(tensor_mat)
print(tensor_mat.ndim)
print(tensor_mat.shape)

tensor([[1, 2]])
2
torch.Size([1, 2])


In [ ]:
tensor_matrix=torch.tensor([1,2,3])
print(tensor_matrix)
print(tensor_matrix.ndim)
print(tensor_matrix.shape)

tensor([1, 2, 3])
1
torch.Size([3])


In [ ]:
device=tensor_matrix.device
device

device(type='cpu')

### Manipulating Tensors (tensor operations)

Tensor operations include:
1) Addition
2) Subtraction
3) Multiplication (element-wise)
4) Division
5) Matrix multiplication

In [ ]:
#Additon
tensor_a=torch.tensor([[[1,2,3,4],[2,3,4,5]]])
tensor_a + 10

tensor([[[11, 12, 13, 14],
         [12, 13, 14, 15]]])

In [ ]:
#Multiply
tensor_a*10

tensor([[[10, 20, 30, 40],
         [20, 30, 40, 50]]])

In [ ]:
#subtract
tensor_a-5

tensor([[[-4, -3, -2, -1],
         [-3, -2, -1,  0]]])

In [ ]:
#Pytorch in-built function for multiplication - torch.mul
torch.mul(tensor_a,3)

tensor([[[ 3,  6,  9, 12],
         [ 6,  9, 12, 15]]])

In [ ]:
torch.add(tensor_a,3)

tensor([[[4, 5, 6, 7],
         [5, 6, 7, 8]]])

In [ ]:
#division
tensor_a/2.5

tensor([[[0.4000, 0.8000, 1.2000, 1.6000],
         [0.8000, 1.2000, 1.6000, 2.0000]]])

In [ ]:
tensor_a/2

tensor([[[0.5000, 1.0000, 1.5000, 2.0000],
         [1.0000, 1.5000, 2.0000, 2.5000]]])

In [ ]:
torch.div(a,2)

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

### Matrix Multiplication

Two main ways of performing multiplication in deep learning and neural networks

1) Element-wise multiplcation

2) Matrix multiplication (dot product)

### There are two main rules that performing matrix multiplication needs to satisfy.

1) The **inner dimensions** must match:
* '(3,2) @ (3.,2)' wont work
* '(2,3) @ (3.2)' will work
* '(3,2) @ (2,3)' will work

2) The resulting matrix has the shape of the **outer dimensions**:
* '(2,3) @ (3,2)' --> '(2,2)'
*'(10,1) @ (1,2)' --> '(10,2)'

@ can be used instead of torch.matmul() for matrix multiplication - but better to use torch.matmul() in initial stages

In [ ]:
#element wise multiplication
tensor_b=torch.tensor([[1,2],[3,4]])
print(tensor_b)
print(tensor_b,"*",tensor_b)
print(tensor_b*tensor_b) # element wise



tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]]) * tensor([[1, 2],
        [3, 4]])
tensor([[ 1,  4],
        [ 9, 16]])


In [ ]:
#matrix multiplication
torch.matmul(tensor_b,tensor_b)

tensor([[ 7, 10],
        [15, 22]])

In [ ]:
tensor_c=torch.tensor([1,2,3])   #shape: 3,1 matrix
torch.matmul(tensor_c,tensor_c)

tensor(14)

### Pytorch in-built function for element wise and matrix multiplication. Very useful when dealing with large matrices.

a) element-wise multiplication: 'torch.mul(x,y)'  
b) matrix multiplication: 'torch.matmul(x,y)' or '@'

where x,y - number, tensor, input

In [ ]:
### matrix mulitplication using '@"
tensor_c @ tensor_c

tensor(14)

In [ ]:
torch.sub(tensor_c,3)

tensor([-2, -1,  0])

In [ ]:
torch.mul(tensor_c,tensor_c)

tensor([1, 4, 9])

In [ ]:
torch.matmul(tensor_c,tensor_c)

tensor(14)

### One of the most common errors in deep learning: shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A=torch.tensor([[1,2],[3,4],[5,6]])   #shape: 3,2
tensor_B=torch.tensor([[7,10],[8,11],[9,12]])   #shape: 3,2

#To fix our tensor shape issues, we can manipulate the shape of one our our tensors
#using a **transpose**
# a **transpose** switches the axes or dimensions of a given tensor
tensor_C=tensor_b.T
torch.mm(tensor_A,tensor_C)

tensor([[ 5, 11],
        [11, 25],
        [17, 39]])

### Finding the min, max, mean, sum, etc (tensor aggregation)


In [ ]:
# Create a tensor
x=torch.arange(1,200,10)
print(x,x.dtype)

tensor([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121, 131,
        141, 151, 161, 171, 181, 191]) torch.int64


In [ ]:
#find the min - (note: irrespective of shape of tensor)
torch.min(x), x.min()  # returns tensor

(tensor(1), tensor(1))

In [ ]:
# find the max - (note: irrespective of shape of tensor)
torch.max(x), x.max()   #returns tensor

(tensor(191), tensor(191))

In [ ]:
# find the mean -(note: irrespective of shape of tensor)
# note: the torch.mean() function requires a input tensor of float32 or complex datatype to work
#torch.mean(x), x.mean() didnt work because x dtype is int64 or long
# so we change it accordingly
torch.mean(x.type(torch.float16)),x.type(torch.float16).mean()  # returns tensor


(tensor(96., dtype=torch.float16), tensor(96., dtype=torch.float16))

In [ ]:
# Find the sum of elements within a tensor -  (note: irrespective of shape of tensor)
torch.sum(x), x.sum()

(tensor(1920), tensor(1920))

### Find the positional min and max

In [ ]:
# find the poisition in tensor that has the minimum value with argmin() --> returns index position of targe tensor where the minimum value occurs
torch.argmin(x), x.argmin() #note - irrespective of shape of tensor

(tensor(0), tensor(0))

In [ ]:
x[0] # 1 is the minimum value in the tensor and 0 is it position as given in above cell

tensor(1)

In [ ]:
# Find the position in tensor that has the maximum value with argmax()
torch.argmax(x),x.argmax() #note - irrespective of shape of tensor

(tensor(19), tensor(19))

In [ ]:
x[19]

tensor(191)

In [ ]:
z=torch.tensor([[[2,3,4],[4,5,6],[6,7,8]]])
print(torch.argmax(z),torch.argmin(z))

tensor(8) tensor(0)


In [ ]:
print(t)
print(t.min())
print(t.max())
print(torch.argmin(t))
print(torch.argmax(t))

tensor([[34, 23],
        [33, 45],
        [22, 23],
        [33, 50],
        [22, 23],
        [33, 50]])
tensor(22)
tensor(50)
tensor(4)
tensor(7)


In [ ]:
u=torch.tensor([[34, 23],[33, 45],[22, 23],[33, 50],[22, 23],[33, 50]])
print(u.min())
print(u.max())
print(u.argmin())
print(u.argmax())

tensor(22)
tensor(50)
tensor(4)
tensor(7)


In [ ]:
print(torch.min(t))
print(torch.max(t))
# print(torch.mean(t))
print(torch.sum(t))

tensor(22)
tensor(50)
tensor(391)


In [ ]:
v=torch.rand(3,2,3,4)
print(v)
print(v.min())
print(v.max())
print(v.argmin())
print(v.argmax())


tensor([[[[0.8020, 0.9562, 0.7383, 0.9550],
          [0.8482, 0.8519, 0.6155, 0.6891],
          [0.8850, 0.4041, 0.6529, 0.2466]],

         [[0.1851, 0.8845, 0.4075, 0.3026],
          [0.3638, 0.5918, 0.3364, 0.3300],
          [0.2004, 0.0542, 0.2845, 0.6745]]],


        [[[0.0321, 0.2498, 0.8716, 0.1558],
          [0.9642, 0.6401, 0.9772, 0.1411],
          [0.9259, 0.4341, 0.1051, 0.1339]],

         [[0.5237, 0.2120, 0.1366, 0.6646],
          [0.8755, 0.5430, 0.4793, 0.7105],
          [0.3749, 0.4556, 0.8027, 0.8953]]],


        [[[0.1474, 0.9509, 0.6310, 0.8950],
          [0.8595, 0.7008, 0.4275, 0.1686],
          [0.2766, 0.9172, 0.5974, 0.7782]],

         [[0.1173, 0.0442, 0.5930, 0.5652],
          [0.3705, 0.1092, 0.5601, 0.8155],
          [0.2464, 0.7742, 0.1718, 0.1407]]]])
tensor(0.0321)
tensor(0.9772)
tensor(24)
tensor(30)


### Reshaping, view, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all 1 dimensions from a tensor
* Unsqueeze - adds a 1 dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
import torch
x=torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#Add an extra dimension
x_reshaped_1 = x.reshape(3,3)
x_reshaped_2=x.reshape(1,9)
x_reshaped_3=x.reshape(9,1)
x_reshaped_4=x.reshape(3,1,3)
# x_reshaped_4=x.reshape(3,2) RuntimeError: shape '[3, 2]' is invalid for input of size 9
print(x_reshaped_1,x_reshaped_1.shape)
print(x_reshaped_2,x_reshaped_2.shape)
print(x_reshaped_3,x_reshaped_3.shape)
print(x_reshaped_4,x_reshaped_4.shape)

tensor([[5., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) torch.Size([3, 3])
tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])
tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]]) torch.Size([9, 1])
tensor([[[5., 2., 3.]],

        [[4., 5., 6.]],

        [[7., 8., 9.]]]) torch.Size([3, 1, 3])


In [ ]:
y=torch.tensor([[1,2],[2,3],[3,4]])
y_reshaped=y.reshape(6,1)
print(y_reshaped)
print(y.ndim, y_reshaped.ndim)

tensor([[1],
        [2],
        [2],
        [3],
        [3],
        [4]])
2 2


In [ ]:
#  Change the view
z=x.view(1,9)
print(x,x.shape)
print(z,z.shape)
# view is same as reshape but it makes the output tensor share the same memory
# as the input tensor. Here, z shares the same memory as x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])
tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])


In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0]=5       # note ':' is to denote to apply for all rows of tensor z
print(x)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


In [ ]:
v.is_contiguous()

True

In [ ]:
v.T.is_contiguous()

/tmp/ipykernel_167/2675541398.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4480.)
  v.T.is_contiguous()


False

In [ ]:
z=v.T.contiguous()
print(z)
print(v.T.is_contiguous())


tensor([[[[0.8020, 0.0321, 0.1474],
          [0.1851, 0.5237, 0.1173]],

         [[0.8482, 0.9642, 0.8595],
          [0.3638, 0.8755, 0.3705]],

         [[0.8850, 0.9259, 0.2766],
          [0.2004, 0.3749, 0.2464]]],


        [[[0.9562, 0.2498, 0.9509],
          [0.8845, 0.2120, 0.0442]],

         [[0.8519, 0.6401, 0.7008],
          [0.5918, 0.5430, 0.1092]],

         [[0.4041, 0.4341, 0.9172],
          [0.0542, 0.4556, 0.7742]]],


        [[[0.7383, 0.8716, 0.6310],
          [0.4075, 0.1366, 0.5930]],

         [[0.6155, 0.9772, 0.4275],
          [0.3364, 0.4793, 0.5601]],

         [[0.6529, 0.1051, 0.5974],
          [0.2845, 0.8027, 0.1718]]],


        [[[0.9550, 0.1558, 0.8950],
          [0.3026, 0.6646, 0.5652]],

         [[0.6891, 0.1411, 0.1686],
          [0.3300, 0.7105, 0.8155]],

         [[0.2466, 0.1339, 0.7782],
          [0.6745, 0.8953, 0.1407]]]])
False


In [ ]:
import torch
y = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

y.transpose(0,1), y.transpose(1,0) #torch.transpose(input, dim0, dim1) → Tensor
#https://docs.pytorch.org/docs/stable/generated/torch.tensor.html#torch.tensor


(tensor([[1, 4],
         [2, 5],
         [3, 6]]),
 tensor([[1, 4],
         [2, 5],
         [3, 6]]))

In [ ]:
z=y.T
print(z)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [ ]:
z.is_contiguous()

False

In [ ]:
z=z.contiguous()
print(z.is_contiguous())

True


In [ ]:
# Stack tensors on top of each other
x_stacked_0=torch.stack([x,x,x,x],dim=0)
print(x,x.ndim,x.shape)
print(x_stacked_0, x_stacked_0.ndim, x_stacked_0.shape)

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]) 1 torch.Size([9])
tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]]) 2 torch.Size([4, 9])


In [ ]:
x_stacked_1=torch.stack([x,x,x,x],dim=1)
print(x,x.ndim,x.shape)
print(x_stacked_1, x_stacked_1.ndim, x_stacked_1.shape)


tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]) 1 torch.Size([9])
tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]]) 2 torch.Size([9, 4])


In [ ]:
x_stacked_2=torch.stack([x,x,x,x],dim=1)
print(x,x.ndim,x.shape)
print(x_stacked_2, x_stacked_2.ndim, x_stacked_2.shape)
# IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)
# thats because original shape of x is incompatible with using dimension 2

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]) 1 torch.Size([9])
tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]]) 2 torch.Size([9, 4])


In [ ]:
#vstack and hstack
i=torch.tensor([1,2,3,4])
j=torch.tensor([5,6,7,8])
k=torch.vstack([i,j])
l=torch.hstack([i,j])
print(i,i.ndim,i.shape)
print(k,k.ndim, k.shape)
print(l,l.ndim,l.shape)

tensor([1, 2, 3, 4]) 1 torch.Size([4])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]]) 2 torch.Size([2, 4])
tensor([1, 2, 3, 4, 5, 6, 7, 8]) 1 torch.Size([8])


### Squeeze and unsqueeze

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
import torch
y=torch.arange(1.,10.)
print("y:",y)

y_reshaped=y.reshape(1,3,3,1)
print("y_reshaped:",y_reshaped)

y: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
y_reshaped: tensor([[[[1.],
          [2.],
          [3.]],

         [[4.],
          [5.],
          [6.]],

         [[7.],
          [8.],
          [9.]]]])


In [ ]:
print(y_reshaped,y_reshaped.shape)
print(y_reshaped.squeeze(dim=-4)) #removes all single dimensions from a target tensor
print(y_reshaped.squeeze(dim=-4).shape)
# if the shape was torch.size([1,1,9]) --> squeeze() will remove all of the 1's and leave 9 alone

tensor([[[[1.],
          [2.],
          [3.]],

         [[4.],
          [5.],
          [6.]],

         [[7.],
          [8.],
          [9.]]]]) torch.Size([1, 3, 3, 1])
tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]],

        [[7.],
         [8.],
         [9.]]])
torch.Size([3, 3, 1])


In [ ]:
#torch.unsqueeze(0 - adds a single dimension to a target tensor at a specific dim (dimension)
print(y_reshaped,y_reshaped.shape)
print(y_reshaped.unsqueeze(dim=0),y_reshaped.unsqueeze(dim=0).shape)
print(y_reshaped.unsqueeze(dim=-1),y_reshaped.unsqueeze(dim=-1).shape)
print(y_reshaped.unsqueeze(0).shape,y_reshaped.unsqueeze(-1).shape)

tensor([[[[1.],
          [2.],
          [3.]],

         [[4.],
          [5.],
          [6.]],

         [[7.],
          [8.],
          [9.]]]]) torch.Size([1, 3, 3, 1])
tensor([[[[[1.],
           [2.],
           [3.]],

          [[4.],
           [5.],
           [6.]],

          [[7.],
           [8.],
           [9.]]]]]) torch.Size([1, 1, 3, 3, 1])
tensor([[[[[1.]],

          [[2.]],

          [[3.]]],


         [[[4.]],

          [[5.]],

          [[6.]]],


         [[[7.]],

          [[8.]],

          [[9.]]]]]) torch.Size([1, 3, 3, 1, 1])
torch.Size([1, 1, 3, 3, 1]) torch.Size([1, 3, 3, 1, 1])


In [ ]:
#torch.perumte - rearranges the dimensions of a target tensor in a specific order
#torch.permute(input, dims) → Tensor : Returns a view of the original tensor input with its dimensions permuted
x_original = torch.rand(size=[224,224,3]) # [height, width, colour channels]

#Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) #shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels,height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
print(x_original[0,0,0])
x_original[0,0,0]=12345
print(x_original[0,0,0])
print(x_permuted[0,0,0])
#torch.permute(input, dims) → Tensor : Returns a view of the original tensor input with its dimensions permuted.

tensor(0.8658)
tensor(12345.)
tensor(12345.)


### Indexing (selecting data from tensors)

#### Indexing with Pytorch is similar to indexing with NumPy.

In [ ]:
# Create a tensor
import torch
x=torch.arange(1,10).reshape(3,3,1)
y=torch.arange(1,10).reshape(1,3,3)
print(x,x.shape)
print(y,y.shape)

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]]) torch.Size([3, 3, 1])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])


In [ ]:
x[0],y[0]

(tensor([[1],
         [2],
         [3]]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

In [ ]:
x[0][0], y[0][0]  # or x[0,0] and y[0,0]

(tensor([1]), tensor([1, 2, 3]))

In [ ]:
y[0,0,0],y[0,0,1],y[0,2,2]

(tensor(1), tensor(2), tensor(9))

In [ ]:
# You can also use ":" to select "all" of a target dimension
# The concept o 'Slicing' allows us to specify ranges or intervals along each dimension to retrieve multiple elements at once.
print(y)
print(y[:]),   # get all of the elements
print(y[0]), # get the 0 th element
print(y[0,:]), # get the 0 th element and then all the elements in the 0th dimension
print(y[:,0]), # get all of the 0th dimension and then the zero th element from that
print(y[:,1])  # get all of the 0th dimension and then the one th element from that


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3]])
tensor([[4, 5, 6]])


In [ ]:
# Get all values of 0th and 1st dimension but only index 1 of 2nd dimension
print(y),
print(y[:]),
print(y[:,:])
print(y[:,:,1])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[2, 5, 8]])


In [ ]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
print(y)
y[:,1,1], y[:,1,1].shape
# consider y[0,1,1] --> tensor(5)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


(tensor([5]), torch.Size([1]))

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
print(y)
print(y[0])
print(y[0,0])
print(y[0,0,:]) # whatever values can come up 2nd dimension in this case will come up

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [ ]:
print(y)
# index on y to return 9
print(y[0,2,2])

# index on y to return 3,6,9 - 2 variations below
print(y[:,:,2])
print(y[0,:,2])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor(9)
tensor([[3, 6, 9]])
tensor([3, 6, 9])


### PyTorch tensors & NumPy
Numpy is a popular scientific Python numerical computing library.
And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor --> torch.from_numpy(ndarray)
* PyTorch tensor to NumPy --> torch.Tensor.numpy()

In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
tensor1=torch.from_numpy(array).type(torch.float32)
print(array, array.dtype)
print(tensor, tensor.dtype)
# warning: when converting from numpy --> pytorch, pytorch reflects numpy's default dataype (float64) unless specified otherwise
print(tensor1,tensor1.dtype)

[1. 2. 3. 4. 5. 6. 7.] float64
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64) torch.float64
tensor([1., 2., 3., 4., 5., 6., 7.]) torch.float32


In [ ]:
# Change the value of array, what will this do to 'tensor'?
array = array + 1
array, tensor
# the value of tensor wont change, if we change value of array. Therefore, both dont share the same memory

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#Tensor to NumPy array
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor, numpy_tensor
#tensor default dtype is float32, so array dtype here will also be float32

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happens to 'numpy_tensor'?
tensor=tensor + 1
tensor, numpy_tensor
# the value of array isnt changed, if tensor is changed. Therefore, both dont share the same memory

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take random out of random)

In short how a neural network learns:

'start with random numbers --> tensor operations --> update random numbers to try and make them better representations of the data --> again --> again --> again...'

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
import torch

#Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.4342, 0.2573, 0.6346, 0.3175],
        [0.6953, 0.4687, 0.1044, 0.6762],
        [0.8929, 0.1024, 0.1740, 0.9536]])
tensor([[0.7879, 0.1178, 0.3219, 0.9090],
        [0.9432, 0.2812, 0.6284, 0.5715],
        [0.9076, 0.2788, 0.7372, 0.7623]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors

import torch
# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED) # this needs to be called everytime before defining a tensor to ensure reproduciblity happens
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Pytorch reproducibility: (extra curricular)
https://docs.pytorch.org/docs/stable/notes/randomness.html
https://en.wikipedia.org/wiki/Random_seed


### Runnin tensors and PyTorch objects on the GPUs ( and making faster computations )

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

1. Getting a GPU

 a) Easiest - Use Google colab for a free GPU (options to upgrade as well)

 b) Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU,there's lots of options.., see this post for what option to get:https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/

 c) Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

 For b,c - PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

In [ ]:
!nvidia-smi

Sat Apr  4 15:45:10 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   43C    P8             12W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

# Check for GPU access with PyTorch

In [ ]:
#https://docs.pytorch.org/docs/stable/cuda.html
#Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, its best practice to setup device agnostic code: https://docs.pytorch.org/docs/stable/notes/cuda.html

E.g. run on GPU if available, else default to CPU

In [ ]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# count the number of devices
print(torch.cuda.device_count())
print(torch.cuda.get_device_name())

1
Tesla T4


### Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPUS is because using a GPU results in faster computations.

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu
#cuda:0 - where 0 is the index of the gpu we are using. we have only one gpu for now
#This code will work because 'device' has been setup in above cell with device agnostic code

## Setup device agnostic code
# device = "cuda" if torch.cuda.is_available() else "cpu"
# device

#when we setup device agnostic code -irrespective of cpu or gpu availaability, the code in this cell works. but if device isnt setup,
#then 'tensor.to(device)' errors out

tensor([1, 2, 3], device='cuda:0')