In [ ]:
print('hello')



hello


In [ ]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
print(torch.__version__)

2.10.0+cpu


**### Introduction to tensors**

In [ ]:
## Introduction to tensors

# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as python int

scalar.item()

7

In [ ]:
# vector
vector=torch.tensor([4,5,6])
vector

tensor([4, 5, 6])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([3])

In [ ]:
# MATRIX

MATRIX = torch.tensor([[2,3,4],[1,2,3],[1,2,3]])
MATRIX

tensor([[2, 3, 4],
        [1, 2, 3],
        [1, 2, 3]])

In [ ]:
MATRIX.ndim  #based on the square bracket pairs - it is 2

2

In [ ]:
MATRIX.shape

torch.Size([3, 3])

In [ ]:
MATRIX[0]

tensor([2, 3, 4])

In [ ]:
print(MATRIX)
print(f"MATRIX[0]:",MATRIX[0])
print(f"MATRIX[1]:",MATRIX[1])
print(f"MATRIX[2]",MATRIX[2])


tensor([[2, 3, 4],
        [1, 2, 3],
        [1, 2, 3]])
MATRIX[0]: tensor([2, 3, 4])
MATRIX[1]: tensor([1, 2, 3])
MATRIX[2] tensor([1, 2, 3])


In [ ]:
#TENSOR
TENSOR = torch.tensor([[[2,3,4],
                        [1,2,3]
                        ]])
TENSOR

tensor([[[2, 3, 4],
         [1, 2, 3]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 2, 3])

In [ ]:
print(TENSOR)
print("TENSOR[0]:",TENSOR[0])



tensor([[[2, 3, 4],
         [1, 2, 3]]])
TENSOR[0]: tensor([[2, 3, 4],
        [1, 2, 3]])


In [ ]:
TENSOR[1]

IndexError: index 1 is out of bounds for dimension 0 with size 1

### Random tensors
## what are they




In [ ]:
## create a random tensor of size (3,4)

tensor1 = torch.rand(4,3,1)
tensor1

tensor([[[0.1395],
         [0.7678],
         [0.2786]],

        [[0.0328],
         [0.0961],
         [0.7141]],

        [[0.5393],
         [0.0103],
         [0.4453]],

        [[0.9273],
         [0.0952],
         [0.3467]]])

In [ ]:
tensor2=torch.rand(3,2)
tensor2


tensor([[0.6371, 0.8807],
        [0.3754, 0.0421],
        [0.7341, 0.2266]])

In [ ]:
tensor3=torch.rand(2)
tensor3

tensor([0.2091, 0.9301])

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=[3,224,224]) # the 3 in dim 0 represents the 3 colour channels - red,green and blue
print(random_image_tensor)
random_image_tensor.ndim, random_image_tensor.shape

tensor([[[0.5754, 0.8654, 0.5639,  ..., 0.9029, 0.6762, 0.0866],
         [0.9902, 0.5236, 0.5062,  ..., 0.0366, 0.0585, 0.2215],
         [0.7829, 0.7436, 0.4572,  ..., 0.3978, 0.9935, 0.6206],
         ...,
         [0.1687, 0.3645, 0.7542,  ..., 0.5451, 0.9078, 0.1625],
         [0.0495, 0.7743, 0.5858,  ..., 0.1894, 0.6151, 0.4861],
         [0.2168, 0.0412, 0.0595,  ..., 0.8428, 0.2332, 0.1098]],

        [[0.9102, 0.4550, 0.4832,  ..., 0.9173, 0.4168, 0.8473],
         [0.3461, 0.0625, 0.0852,  ..., 0.0334, 0.4738, 0.9769],
         [0.8822, 0.9292, 0.9022,  ..., 0.0513, 0.5301, 0.6969],
         ...,
         [0.0638, 0.8811, 0.2713,  ..., 0.1388, 0.5303, 0.2670],
         [0.2409, 0.7467, 0.8115,  ..., 0.5649, 0.1855, 0.5245],
         [0.3200, 0.8217, 0.8840,  ..., 0.0787, 0.5769, 0.9120]],

        [[0.6904, 0.6583, 0.2609,  ..., 0.0100, 0.0520, 0.5801],
         [0.9080, 0.7385, 0.9875,  ..., 0.2562, 0.6939, 0.4664],
         [0.9436, 0.5309, 0.4125,  ..., 0.8769, 0.8915, 0.

(3, torch.Size([3, 224, 224]))

###Zeros and ones



In [ ]:
# Create a tensor of zeros
zeros=torch.zeros(3,4)
print(zeros)
print(zeros.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32


In [ ]:
zer1=torch.zeros(size=[2,3,1])
print(zer1)
print(zer1.dtype)

tensor([[[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]]])
torch.float32


In [ ]:
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
new_tensor=torch.rand(3,4)
new_tensor_0=zeros*new_tensor
new_tensor_1=ones*new_tensor
print(new_tensor)
print(new_tensor_0)
print(new_tensor_1)

tensor([[0.7991, 0.6747, 0.8542, 0.0057],
        [0.9261, 0.3895, 0.9585, 0.4307],
        [0.6219, 0.0672, 0.9459, 0.7899]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0.7991, 0.6747, 0.8542, 0.0057],
        [0.9261, 0.3895, 0.9585, 0.4307],
        [0.6219, 0.0672, 0.9459, 0.7899]])


### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range() and get deprecated message, use torch.arange() instead as per UserWarning
torch.range(0,10)

/tmp/ipython-input-3858421243.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.arange(10,0,-1)

tensor([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
# Creating tensors like
a=torch.tensor([[1,2,3],[4,5,6]])
b=torch.arange(22,44,2)
c=torch.zeros_like(a)
print(c)
d=torch.zeros_like(input=b)
print(d)
e=torch.ones_like(d)
print(e)

tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


#Tensor Datatypes
### Note: Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not right device

In [ ]:
# Float 32 tensor (default)
float_32_tensor = torch.tensor([1.0,2.0,3.2],
                               dtype=None,# what datatype is the tensor ex:float32(default) or float16
                               device=None,# what device is your tensor on ex: cpu(default) or cuda
                               requires_grad=False) # whether or not to track gradients with this tensor's operations
print(float_32_tensor)
print(float_32_tensor.dtype)

# The default datatype is going to come out as float32 even if dtype is specified as None ( and float type numbers are used to create tensor).
# 'FP32' or 'float32' or '32-bit floating point' or 'single-precision floating point format'
# 'FP16' or 'float16' or '16-bit floating point' or 'half-precision floating point format'
# 'FP64' or 'float64' or '64-bit floating point' or 'double-precision floating point format'

#In computer science, precision refers to how accurately a computer can represent and calculate numbers, especially decimal or fractional values.
# It’s about how many digits (or bits) are used to store a number, which determines how close the stored value is to the actual mathematical value.

tensor([1.0000, 2.0000, 3.2000])
torch.float32


In [ ]:
# Convertin float32 to another dtype
float_16_tensor_a=float_32_tensor.type(torch.float16)
float_16_tensor_b=float_32_tensor.type(torch.half)
print(float_16_tensor_a,float_16_tensor_a.dtype)
print(float_16_tensor_b,float_16_tensor_b.dtype)


tensor([1.0000, 2.0000, 3.1992], dtype=torch.float16) torch.float16
tensor([1.0000, 2.0000, 3.1992], dtype=torch.float16) torch.float16


In [ ]:
#defining the dtype while creating the tensor, if it shouldn't be default float32
float_64_tensor= torch.tensor([2.0,3.0,4.0],
                                dtype=torch.float64,
                                )
float_64_tensor.dtype

torch.float64

In [ ]:
d=float_32_tensor*float_64_tensor
e=float_32_tensor+float_64_tensor
print(float_32_tensor,float_64_tensor)
print(d,d.dtype)
print(e,e.dtype)

tensor([1.0000, 2.0000, 3.2000]) tensor([2., 3., 4.], dtype=torch.float64)
tensor([ 2.0000,  6.0000, 12.8000], dtype=torch.float64) torch.float64
tensor([3.0000, 5.0000, 7.2000], dtype=torch.float64) torch.float64



Getting information from tensors(Tensor attributes):

1.	Tensors not right datatype – to get datatype from a tensor, type tensor.dtype

2.	Tensors not right shape – to get shape from a tensor, type tensor.shape

3.	Tensors not right device – to get device from a tensor, type tensor.device


In [1]:
!git clone https://github.com/ranjithrajappa/pytorch-for-deep-learning-and-machine-learning.git

Cloning into 'pytorch-for-deep-learning-and-machine-learning'...


In [2]:
%cd /content/pytorch-for-deep-learning-and-machine-learning
!pwd

/content/pytorch-for-deep-learning-and-machine-learning
/content/pytorch-for-deep-learning-and-machine-learning


In [3]:
!mkdir notebooks
!mkdir src

In [4]:
!touch README.md

In [5]:
!ls


notebooks  README.md  src


In [6]:
!mv /content 00_pytorch_fundamentals.ipynb notebooks/

mv: cannot move '/content' to a subdirectory of itself, 'notebooks/content'
mv: cannot stat '00_pytorch_fundamentals.ipynb': No such file or directory


In [7]:
!pwd

/content/pytorch-for-deep-learning-and-machine-learning


In [8]:
!mv /content/00_pytorch_fundamentals.ipynb notebooks/

mv: cannot stat '/content/00_pytorch_fundamentals.ipynb': No such file or directory


In [9]:
!ls /content
!ls

drive  pytorch-for-deep-learning-and-machine-learning  sample_data
notebooks  README.md  src


In [10]:
!ls /content

drive  pytorch-for-deep-learning-and-machine-learning  sample_data
